import Link from 'next/link';

export default function Analysis({ params }) {
  const { slug } = params;

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">Market Analysis: {slug.replace('-', '/').toUpperCase()}</h1>
          <p className="text-[#3a6070]">{new Date().toLocaleDateString()}</p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2">
            <div className="bg-[#111e2e] border border-[#1a2e42] rounded-lg p-6 mb-6">
              <h2 className="text-xl font-semibold mb-4">Analysis Content</h2>
              <p className="text-[#3a6070] mb-4">
                This is a placeholder for the detailed market analysis article.
                The full analysis will include technical indicators, price action analysis,
                and AI-generated trading recommendations.
              </p>
              <div className="bg-[#080d14] border border-[#1a2e42] rounded p-4">
                <h3 className="font-semibold mb-2">Key Points</h3>
                <ul className="text-sm text-[#3a6070] space-y-1">
                  <li>• Technical analysis based on multiple timeframes</li>
                  <li>• AI-powered signal generation</li>
                  <li>• Risk management recommendations</li>
                  <li>• Market sentiment indicators</li>
                </ul>
              </div>
            </div>

            {/* Related Articles */}
            <div className="bg-[#111e2e] border border-[#1a2e42] rounded-lg p-6">
              <h2 className="text-xl font-semibold mb-4">Related Analysis</h2>
              <div className="space-y-3">
                <div className="border-b border-[#1a2e42] pb-3">
                  <a href="/analysis/eur-usd" className="text-[#60c8d4] hover:text-[#4da8b3] font-medium">
                    EUR/USD Technical Analysis
                  </a>
                  <p className="text-sm text-[#3a6070] mt-1">Latest signals and market outlook</p>
                </div>
                <div className="border-b border-[#1a2e42] pb-3">
                  <a href="/analysis/us500" className="text-[#60c8d4] hover:text-[#4da8b3] font-medium">
                    US500 Index Analysis
                  </a>
                  <p className="text-sm text-[#3a6070] mt-1">Stock market trends and predictions</p>
                </div>
              </div>
            </div>
          </div>

          {/* Sidebar */}
          <div>
            <div className="bg-[#111e2e] border border-[#1a2e42] rounded-lg p-6 mb-6">
              <h3 className="font-semibold mb-4">Signal Score</h3>
              <div className="text-center">
                <div className="text-3xl font-bold text-[#1D9E75] mb-2">85</div>
                <div className="text-sm text-[#3a6070]">TRADE Signal</div>
              </div>
              <div className="mt-4 space-y-2 text-sm">
                <div className="flex justify-between">
                  <span>ADX:</span>
                  <span>28.5</span>
                </div>
                <div className="flex justify-between">
                  <span>Direction:</span>
                  <span>BULLISH</span>
                </div>
              </div>
            </div>

            <div className="bg-[#111e2e] border border-[#1a2e42] rounded-lg p-6">
              <h3 className="font-semibold mb-4">Quick Links</h3>
              <div className="space-y-2">
                <Link href="/" className="block text-[#60c8d4] hover:text-[#4da8b3] text-sm">
                  Forex Markets
                </Link>
                <Link href="/indices" className="block text-[#60c8d4] hover:text-[#4da8b3] text-sm">
                  Indices Markets
                </Link>
                <Link href="/subscribe" className="block text-[#60c8d4] hover:text-[#4da8b3] text-sm">
                  Subscribe for Updates
                </Link>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <footer className="mt-16 bg-[#111e2e] border-t border-[#1a2e42] py-8 rounded-lg text-center">
          <div className="flex flex-wrap justify-center gap-6 mb-4">
            <Link href="/" className="text-[#c8dce8] hover:text-[#60c8d4]">Home</Link>
            <Link href="/forex" className="text-[#c8dce8] hover:text-[#60c8d4]">Forex</Link>
            <Link href="/indices" className="text-[#c8dce8] hover:text-[#60c8d4]">Indices</Link>
            <Link href="/subscribe" className="text-[#c8dce8] hover:text-[#60c8d4]">Subscribe</Link>
          </div>
          <p className="text-[#3a6070] text-sm">
            Data powered by cTrader/Pepperstone. Analysis generated by AI.
          </p>
        </footer>
      </div>
    </div>
  );
}