import { NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { createArticle } from '../../../lib/articles';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function POST(request) {
  try {
    const authHeader = request.headers.get('authorization');
    if (authHeader !== 'Bearer ' + process.env.PUBLISH_SECRET) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const signal = await request.json();
    const { ticker, direction, score, adx, rsi, entry_price, stop_loss, 
            take_profit, rr_ratio, entry_mode, sl_reason, rating } = signal;

    const arrow = direction === 'LONG' ? '▲' : '▼';
    const ratingLabel = score >= 8 ? 'TRADE' : score >= 4 ? 'WATCH' : 'AVOID';

    const prompt = `Write a professional trading signal analysis article for ${ticker}.

Signal Details:
- Direction: ${direction} ${arrow}
- Score: ${score}/10
- Rating: ${ratingLabel}
- Entry: ${entry_price}
- Stop Loss: ${stop_loss}
- Take Profit: ${take_profit}
- R:R Ratio: ${rr_ratio}:1
- ADX: ${adx}
- RSI: ${rsi}
- Entry Mode: ${entry_mode}
- SL Logic: ${sl_reason}

Requirements:
- 500-600 words
- Professional trading analysis tone
- Explain WHY this signal qualifies (reference the score factors: trend alignment, ADX strength, RSI position, EMA alignment)
- Explain the entry mode (${entry_mode === 'SWEEP' ? 'liquidity sweep detected' : 'standard structure entry'})
- Explain the stop loss placement logic
- Include risk management reminder (never risk more than 1-2% per trade)
- Format as clean HTML with <h2> subheadings and <p> paragraphs
- Do not include <html>, <head>, <body> tags
- Do not repeat the signal numbers in prose — they are shown in the signal card`;

    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-5',
      max_tokens: 1500,
      messages: [{ role: 'user', content: prompt }]
    });

    const content = response.content[0].text;
    const excerpt = content.replace(/<[^>]*>/g, '').substring(0, 200) + '...';
    const timestamp = Date.now();
    const slug = `${ticker.toLowerCase()}-${direction.toLowerCase()}-signal-${timestamp}`;
    const title = `${ticker} ${direction} Signal — Score ${score}/10 · ${entry_mode} Entry`;
    const seoTitle = `${ticker} ${ratingLabel} Signal: Score ${score}/10 | MaxTradeFlow`;
    const seoDescription = `${ticker} ${direction} trading signal. Score ${score}/10, ADX ${adx}, RSI ${rsi}. ${entry_mode} entry at ${entry_price}. Generated by Smart Asset Bot.`;

    const article = await createArticle({
      slug,
      title,
      excerpt,
      content,
      ticker,
      category: 'signal',
      rating: ratingLabel,
      score,
      adx,
      rsi,
      direction,
      entry_mode,
      tags: [ticker, direction, ratingLabel, entry_mode, 'signal'],
      seo_title: seoTitle,
      seo_description: seoDescription,
      published: true,
    });

    return NextResponse.json({ 
      success: true, 
      article_slug: slug,
      article_url: '/articles/' + slug
    });

  } catch (error) {
    console.error('Publish signal error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}