import { NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { neon } from '@neondatabase/serverless';
import { isAuthorized } from '@/lib/signal-auth';
import { getInstrument } from '@/lib/instruments';

function getDb() {
  return neon(process.env.NEON_DATABASE_URL);
}

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

/**
 * Generate the analysis article and insert it (existing behavior, shared by v1
 * and v2). The INSERT deliberately does NOT reference articles.signal_uid so it
 * is identical to the pre-v2 statement and safe whether or not the migration
 * has run. v2 links the FK with a separate UPDATE afterwards.
 * Returns the created/updated article slug.
 */
async function createArticle(sql, signal) {
  const { ticker, direction, score, adx, rsi, entry_price, stop_loss,
          take_profit, rr_ratio, entry_mode, sl_reason } = signal;

  const arrow = direction === 'LONG' ? '▲' : '▼';
  const ratingLabel = score >= 8 ? 'TRADE' : score >= 4 ? 'WATCH' : 'AVOID';

  const prompt = `Write a professional trading signal analysis article for ${ticker}.

Signal Details:
- Direction: ${direction} ${arrow}
- Score: ${score}/10
- Rating: ${ratingLabel}
- Entry: ${entry_price}
- Stop Loss: ${stop_loss}
- Take Profit: ${take_profit}
- R:R Ratio: ${rr_ratio}:1
- ADX: ${adx}
- RSI: ${rsi}
- Entry Mode: ${entry_mode}
- SL Logic: ${sl_reason}

Requirements:
- 500-600 words
- Professional trading analysis tone
- Explain WHY this signal qualifies (reference the score factors: trend alignment, ADX strength, RSI position, EMA alignment)
- Explain the entry mode (${entry_mode === 'SWEEP' ? 'liquidity sweep detected' : 'standard structure entry'})
- Explain the stop loss placement logic
- Include risk management reminder (never risk more than 1-2% per trade)
- Format as clean HTML with <h2> subheadings and <p> paragraphs
- Do not include <html>, <head>, <body> tags
- Do not repeat the signal numbers in prose — they are shown in the signal card`;

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-5',
    max_tokens: 1500,
    messages: [{ role: 'user', content: prompt }]
  });

  const content = response.content[0].text;
  const excerpt = content.replace(/<[^>]*>/g, '').substring(0, 200) + '...';
  const timestamp = Date.now();
  const slug = `${ticker.toLowerCase()}-${direction.toLowerCase()}-signal-${timestamp}`;
  const title = `${ticker} ${direction} Signal — Score ${score}/10 · ${entry_mode} Entry`;
  const seoTitle = `${ticker} ${ratingLabel} Signal: Score ${score}/10 | MaxTradeFlow`;
  const seoDescription = `${ticker} ${direction} trading signal. Score ${score}/10, ADX ${adx}, RSI ${rsi}. ${entry_mode} entry at ${entry_price}. Generated by Smart Asset Bot.`;

  await sql`
    INSERT INTO articles (
      slug, title, excerpt, content, ticker, category, rating,
      score, adx, rsi, direction, entry_mode, tags,
      seo_title, seo_description, published,
      entry_price, stop_loss, take_profit, rr_ratio
    ) VALUES (
      ${slug}, ${title}, ${excerpt}, ${content},
      ${ticker}, ${'signal'}, ${ratingLabel},
      ${score}, ${adx}, ${rsi}, ${direction}, ${entry_mode},
      ${[ticker, direction, ratingLabel, entry_mode, 'signal']},
      ${seoTitle}, ${seoDescription}, ${true},
      ${entry_price || null}, ${stop_loss || null}, ${take_profit || null}, ${rr_ratio || null}
    )
    ON CONFLICT (slug) DO UPDATE SET
      content = EXCLUDED.content,
      updated_at = NOW()
    RETURNING *
  `;
  return slug;
}

/**
 * v1 (legacy) path — current production bot. Behavior is intentionally
 * identical to the pre-v2 endpoint: generate + store the article, nothing else.
 * No signals row, no FK. Untouched so the live pipeline cannot break.
 */
async function handleV1(sql, signal) {
  const slug = await createArticle(sql, signal);
  return NextResponse.json({
    success: true,
    article_slug: slug,
    article_url: '/articles/' + slug
  });
}

/**
 * v2 path (§6 contract). Writes the immutable signals row, seeds the GENERATED
 * lifecycle event, creates the article (idempotently per signal_uid), and links
 * the FK. Idempotent on signal_uid: a repeated publish returns the existing
 * article without re-generating.
 */
async function handleV2(sql, signal) {
  const {
    signal_uid, ticker, asset_class, direction, entry_price, stop_loss,
    take_profit, rr_ratio, score, tradeflow_score, tfs_version, confidence,
    adx, rsi, entry_mode, sl_reason, reasons, market_condition, session,
    expected_duration, generated_at,
  } = signal;

  if (!signal_uid || !ticker || !direction) {
    return NextResponse.json(
      { error: 'v2 payload requires signal_uid, ticker and direction' },
      { status: 400 }
    );
  }

  const assetClass = asset_class || getInstrument(ticker)?.assetClass || null;
  const occurredAt = generated_at || new Date().toISOString();

  // Immutable signal record (idempotent on signal_uid).
  await sql`
    INSERT INTO signals (
      signal_uid, schema_version, ticker, asset_class, direction,
      entry_price, stop_loss, take_profit, rr_ratio, score,
      tradeflow_score, tfs_version, confidence, adx, rsi,
      entry_mode, sl_reason, reasons, market_condition, session,
      expected_duration, generated_at, status
    ) VALUES (
      ${signal_uid}, 2, ${ticker}, ${assetClass}, ${direction},
      ${entry_price ?? null}, ${stop_loss ?? null}, ${take_profit ?? null}, ${rr_ratio ?? null}, ${score ?? null},
      ${tradeflow_score ?? null}, ${tfs_version ?? null}, ${confidence ?? null}, ${adx ?? null}, ${rsi ?? null},
      ${entry_mode ?? null}, ${sl_reason ?? null}, ${JSON.stringify(reasons ?? null)}, ${market_condition ?? null}, ${session ?? null},
      ${expected_duration ?? null}, ${generated_at ?? null}, 'GENERATED'
    )
    ON CONFLICT (signal_uid) DO NOTHING
  `;

  // Seed the GENERATED lifecycle event (idempotent on signal_uid+event_type).
  await sql`
    INSERT INTO signal_events (signal_uid, event_type, price, occurred_at)
    VALUES (${signal_uid}, 'GENERATED', ${entry_price ?? null}, ${occurredAt})
    ON CONFLICT (signal_uid, event_type) DO NOTHING
  `;

  // Idempotent on signal_uid: if the article already exists, don't regenerate.
  const existing = await sql`
    SELECT slug FROM articles WHERE signal_uid = ${signal_uid} LIMIT 1`;
  if (existing.length > 0) {
    return NextResponse.json({
      success: true,
      idempotent: true,
      signal_uid,
      article_slug: existing[0].slug,
      article_url: '/articles/' + existing[0].slug,
    });
  }

  const slug = await createArticle(sql, signal);
  await sql`UPDATE articles SET signal_uid = ${signal_uid} WHERE slug = ${slug}`;

  return NextResponse.json({
    success: true,
    signal_uid,
    article_slug: slug,
    article_url: '/articles/' + slug,
  });
}

export async function POST(request) {
  try {
    if (!isAuthorized(request)) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const signal = await request.json();
    const sql = getDb();
    const version = signal.schema_version;

    // Missing schema_version = legacy v1 (current production bot). During the
    // transition we must keep accepting it. A present-but-unsupported version
    // is rejected.
    if (version === undefined || version === null) {
      return await handleV1(sql, signal);
    }
    if (Number(version) === 2) {
      return await handleV2(sql, signal);
    }
    return NextResponse.json(
      { error: `Unsupported schema_version: ${version}` },
      { status: 400 }
    );
  } catch (error) {
    console.error('Publish signal error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
