'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { fetchPrices, fetchScreener } from '../../lib/api';

export default function Indices() {
  const [prices, setPrices] = useState([]);
  const [screener, setScreener] = useState([]);

  useEffect(() => {
    fetchPrices().then(setPrices);
    fetchScreener().then(setScreener);

    const interval = setInterval(() => {
      fetchPrices().then(setPrices);
    }, 5000);

    return () => clearInterval(interval);
  }, []);

  const indexPairs = prices.filter(price =>
    price.symbol.includes('US500') || price.symbol.includes('NAS100') || price.symbol.includes('US30')
  );

  const indexSignals = screener.filter(signal =>
    signal.symbol.includes('US500') || signal.symbol.includes('NAS100') || signal.symbol.includes('US30')
  );

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-[#9333ea] mb-4">Indices Markets</h1>
          <p className="text-[#3a6070] text-lg">Live prices and AI-powered trading signals</p>
        </div>

        {/* Live Prices Grid */}
        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-6">Live Prices</h2>
          <div className="bg-[#111e2e] border border-[#1a2e42] rounded-lg overflow-hidden">
            <div className="grid grid-cols-4 gap-4 p-4 bg-[#1a2e42] font-semibold text-sm">
              <div>Symbol</div>
              <div>Bid</div>
              <div>Ask</div>
              <div>Spread</div>
            </div>
            {indexPairs.map((price, index) => (
              <div key={index} className="grid grid-cols-4 gap-4 p-4 border-t border-[#1a2e42] text-sm">
                <div className="font-medium">{price.symbol}</div>
                <div className="text-[#9333ea]">{price.bid}</div>
                <div className="text-[#9333ea]">{price.ask}</div>
                <div className="text-[#3a6070]">{price.spread}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Signal Scores Table */}
        <section>
          <h2 className="text-2xl font-semibold mb-6">Signal Scores</h2>
          <div className="bg-[#111e2e] border border-[#1a2e42] rounded-lg overflow-hidden">
            <div className="grid grid-cols-5 gap-4 p-4 bg-[#1a2e42] font-semibold text-sm">
              <div>Symbol</div>
              <div>Score</div>
              <div>ADX</div>
              <div>Direction</div>
              <div>Action</div>
            </div>
            {indexSignals.map((signal, index) => (
              <div key={index} className="grid grid-cols-5 gap-4 p-4 border-t border-[#1a2e42] text-sm">
                <div className="font-medium">{signal.symbol}</div>
                <div>{signal.score}</div>
                <div>{signal.adx}</div>
                <div>{signal.direction}</div>
                <span className={`px-2 py-1 rounded text-xs font-medium ${
                  signal.action === 'TRADE' ? 'bg-[#1D9E75] text-white' :
                  signal.action === 'WATCH' ? 'bg-[#EF9F27] text-white' :
                  'bg-[#e05555] text-white'
                }`}>
                  {signal.action}
                </span>
              </div>
            ))}
          </div>
        </section>

        {/* Footer */}
        <footer className="mt-16 bg-[#111e2e] border-t border-[#1a2e42] py-8 rounded-lg text-center">
          <div className="flex flex-wrap justify-center gap-6 mb-4">
            <Link href="/" className="text-[#c8dce8] hover:text-[#60c8d4]">Home</Link>
            <Link href="/forex" className="text-[#c8dce8] hover:text-[#60c8d4]">Forex</Link>
            <Link href="/indices" className="text-[#c8dce8] hover:text-[#60c8d4]">Indices</Link>
            <Link href="/subscribe" className="text-[#c8dce8] hover:text-[#60c8d4]">Subscribe</Link>
          </div>
          <p className="text-[#3a6070] text-sm">
            Data powered by cTrader/Pepperstone. Analysis generated by AI.
          </p>
        </footer>
      </div>
    </div>
  );
}