// components/Footer.js
import Link from "next/link";

export default function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="bg-[#111e2e] border-t border-[#1a2e42] text-[#c8dce8] mt-12">
      <div className="max-w-7xl mx-auto px-6 py-10">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">

          {/* Brand */}
          <div className="md:col-span-1">
            <div className="text-[#60c8d4] font-bold text-xl mb-2">MaxTradeFlow</div>
            <p className="text-xs text-[#3a6070] leading-relaxed">
              AI-powered market analysis. Free educational signals from the Smart Asset Bot.
            </p>
          </div>

          {/* Markets */}
          <div>
            <p className="text-xs uppercase text-[#3a6070] font-semibold mb-3 tracking-wide">Markets</p>
            <Link href="/forex" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Forex</Link>
            <Link href="/indices" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Indices</Link>
            <Link href="/commodities" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Commodities</Link>
            <Link href="/crypto" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Crypto</Link>
            <Link href="/stocks" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Stocks</Link>
          </div>

          {/* Tools & Learn */}
          <div>
            <p className="text-xs uppercase text-[#3a6070] font-semibold mb-3 tracking-wide">Tools & Learn</p>
            <Link href="/tools" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Calculators</Link>
            <Link href="/articles" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Signals & Articles</Link>
            <Link href="/education" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Education</Link>
            <Link href="/guides" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Guides</Link>
          </div>

          {/* Company */}
          <div>
            <p className="text-xs uppercase text-[#3a6070] font-semibold mb-3 tracking-wide">Company</p>
            <Link href="/about" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">About</Link>
            <Link href="/contact" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Contact</Link>
            <Link href="/privacy" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Privacy Policy</Link>
            <Link href="/terms" className="block text-sm text-[#c8dce8] hover:text-[#60c8d4] py-1">Terms of Service</Link>
          </div>
        </div>

        {/* Risk disclaimer */}
        <div className="border-t border-[#1a2e42] pt-6 mb-4">
          <p className="text-xs text-[#3a6070] leading-relaxed">
            <span className="text-[#c8dce8] font-semibold">Risk warning:</span> Trading carries substantial risk and may not be suitable for all investors.
            Signals and analysis on MaxTradeFlow are generated by automated systems for educational purposes only and do not constitute financial advice.
            Past performance is not indicative of future results. You are solely responsible for your trading decisions.
            See our <Link href="/terms" className="text-[#60c8d4] hover:underline">Terms of Service</Link>.
          </p>
        </div>

        {/* Bottom row */}
        <div className="border-t border-[#1a2e42] pt-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-3">
          <div className="text-xs text-[#3a6070]">
            © {year} MaxTradeFlow · Built by Mark Hillary
          </div>
          <div className="text-xs text-[#3a6070]">
            Powered by Next.js · Hosted on Vercel · Data from Smart Asset Bot, Finnhub & TradingView
          </div>
        </div>
      </div>
    </footer>
  );
}