import Link from 'next/link';
import { getArticlesByCategory } from '../../lib/articles';

export const metadata = {
  title: 'Market Signals | MaxTradeFlow',
  description: 'Live trading signals generated by Smart Asset Bot across Forex, Indices and Commodities',
};

export default async function ArticlesPage() {
  const articles = await getArticlesByCategory('signal', 50);

  return (
    <div style={{ minHeight: '100vh', background: '#080d14' }}>
      <div style={{ padding: '40px 24px', textAlign: 'center', background: '#111e2e', borderBottom: '0.5px solid #1a2e42' }}>
        <h1 style={{ fontSize: '32px', color: '#c8dce8', marginBottom: '12px', fontWeight: '600' }}>Market Signals</h1>
        <p style={{ color: '#3a6070', fontSize: '15px' }}>AI-generated analysis for every signal fired by Smart Asset Bot</p>
      </div>
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '32px 24px' }}>
        {articles.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '60px', color: '#3a6070' }}>
            <p style={{ fontSize: '16px', marginBottom: '8px' }}>No signals published yet.</p>
            <p style={{ fontSize: '13px' }}>Articles are auto-generated when the bot fires a signal.</p>
          </div>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '16px' }}>
            {articles.map(article => {
              const ratingColor = article.rating === 'TRADE' ? '#1D9E75' : article.rating === 'WATCH' ? '#EF9F27' : '#e05555';
              return (
                <Link key={article.slug} href={'/articles/' + article.slug} style={{ textDecoration: 'none' }}>
                  <div style={{ background: '#111e2e', border: '0.5px solid #1a2e42', borderRadius: '12px', padding: '20px', cursor: 'pointer' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                      <span style={{ fontSize: '13px', fontWeight: '600', color: '#c8dce8' }}>{article.ticker}</span>
                      <span style={{ padding: '3px 10px', background: ratingColor, borderRadius: '20px', fontSize: '11px', color: '#fff', fontWeight: '600' }}>{article.rating}</span>
                    </div>
                    <h3 style={{ fontSize: '14px', color: '#c8dce8', fontWeight: '500', marginBottom: '8px', lineHeight: '1.4' }}>{article.title}</h3>
                    <p style={{ fontSize: '12px', color: '#3a6070', lineHeight: '1.6', marginBottom: '12px' }}>{article.excerpt}</p>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11px', color: '#3a6070' }}>
                      <span>{new Date(article.created_at).toLocaleDateString()}</span>
                      <span>{article.score}/10</span>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
