export const revalidate = 0;

import { getArticlesByCategory } from '../../lib/articles';
import ArticlesClient from './ArticlesClient';

const PAGE_SIZE = 12;

export const metadata = {
  title: 'Market Signals | MaxTradeFlow',
  description: 'Live trading signals generated by Smart Asset Bot across Forex, Indices and Commodities',
};

export default async function ArticlesPage({ searchParams }) {
  const params = await searchParams;
  const page = parseInt(params?.page || '1');
  const all = await getArticlesByCategory('signal', 200);
  const total = all.length;
  const totalPages = Math.ceil(total / PAGE_SIZE);
  const articles = all.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  return (
    <ArticlesClient
      articles={articles}
      total={total}
      page={page}
      totalPages={totalPages}
    />
  );
}