import { NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { neon } from '@neondatabase/serverless';

function getDb() {
  return neon(process.env.NEON_DATABASE_URL);
}

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function POST(request) {
  try {
    const authHeader = request.headers.get('authorization');
    if (authHeader !== 'Bearer ' + process.env.PUBLISH_SECRET) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { date, top_setups, market_summary } = body;

    const sql = getDb();
    const recentSignals = await sql`
      SELECT ticker, direction, score, adx FROM articles 
      WHERE category = 'signal'
        AND published = true
        AND (is_valid IS NULL OR is_valid = true)
      ORDER BY created_at DESC LIMIT 10
    `;

    const signalSummary = recentSignals
      .map(a => `${a.ticker} ${a.direction} score=${a.score} adx=${a.adx}`)
      .join(', ');

    const prompt = `Write a forward-looking daily market outlook article for traders.

Date: ${date}
Top setups being watched by Smart Asset Bot: ${top_setups || signalSummary || 'Various Forex and Indices pairs'}
Market context: ${market_summary || 'Standard market conditions'}

Requirements:
- 600-800 words
- Forward-looking — what traders should watch TODAY and TOMORROW
- Cover: which instruments are building momentum (ADX rising), 
  key levels to watch, which sessions are likely most active,
  setups that are close to triggering (score 6-7 watching for 8+)
- Include practical advice: what to look for before entering,
  patience reminder, risk management
- Tone: professional morning briefing, like a senior trader talking to their team
- Format as clean HTML with <h2> subheadings and <p> paragraphs
- Do not include <html>, <head>, <body> tags
- End with: "Smart Asset Bot is scanning 15 instruments every minute. 
  When a setup reaches 8/10, we publish the full signal analysis automatically."`;

    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-5',
      max_tokens: 2000,
      messages: [{ role: 'user', content: prompt }]
    });

    const content = response.content[0].text;
    const excerpt = content.replace(/<[^>]*>/g, '').substring(0, 200) + '...';
    const today = new Date().toISOString().split('T')[0];
    const slug = `morning-outlook-${today}`;
    const title = `Morning Market Outlook — ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}`;

    const article = await createArticle({
      slug,
      title,
      excerpt,
      content,
      ticker: null,
      category: 'outlook',
      rating: null,
      score: null,
      adx: null,
      rsi: null,
      direction: null,
      entry_mode: null,
      tags: ['morning outlook', 'market analysis', 'daily briefing', today],
      seo_title: title + ' | MaxTradeFlow',
      seo_description: 'Daily forward-looking market analysis and trading setups to watch. Generated by Smart Asset Bot.',
      published: true,
    });

    return NextResponse.json({ 
      success: true, 
      article_slug: slug,
      article_url: '/articles/' + slug
    });

  } catch (error) {
    console.error('Morning outlook error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}